# Generated by Django 4.2.7 on 2026-04-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='upi_qr',
            field=models.ImageField(blank=True, help_text='Upload your own UPI QR Code image', null=True, upload_to='shop/qrs/'),
        ),
    ]
