# Generated by Django 4.2.7 on 2026-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopprofile',
            options={'verbose_name': 'Shop Profile', 'verbose_name_plural': 'Shop Profiles'},
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Official shop email address', max_length=254),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='pincode',
            field=models.CharField(blank=True, help_text='Area PIN code', max_length=10),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State for GST purposes', max_length=50),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number for communication', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full physical address'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='gst_no',
            field=models.CharField(blank=True, help_text='GST Identification Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Primary contact mobile', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_name',
            field=models.CharField(blank=True, help_text='Official name of the shop', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='terms',
            field=models.TextField(blank=True, help_text='Default terms and conditions for bills'),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for digital payments', max_length=50),
        ),
        migrations.AlterModelTable(
            name='shopprofile',
            table='users_shopprofile',
        ),
    ]
