# Generated by Django 5.2.10 on 2026-04-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shopprofile_upi_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_end_date',
        ),
    ]
